### ISSUE TITLE
not handling "?" in url

### ISSUE THREAD

**Issue by mrsfixit** [jhawthorn/curl-to-ruby#3]
![screen shot 2016-06-14 at 11 39 51 am](https://cloud.githubusercontent.com/assets/8654692/16028679/ededbeae-3224-11e6-8c60-28af46e72822.png)

**Comment by jhawthorn** [comment]
Thanks for reporting. It was being too smart at shell parsing, and assumed the `?` was part of a glob. It now ignores globs
